# Generated by Django 4.0.5 on 2022-07-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('physical_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(null=True, upload_to='pics')),
                ('discount', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stock_count', models.IntegerField()),
                ('img', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('model_no', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('rom', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('previous_price', models.FloatField()),
                ('current_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_dress', models.BooleanField()),
                ('women_dress', models.BooleanField()),
                ('babies_dress', models.BooleanField()),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(null=True, upload_to='pics')),
                ('current_price', models.FloatField()),
                ('previous_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
    ]
