# Generated by Django 4.0.5 on 2022-07-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_view_image', models.ImageField(null=True, upload_to='pics')),
                ('rare_view_image', models.ImageField(null=True, upload_to='pics')),
                ('side_view_image', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='blazer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='jacket',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='jeans',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='jumpsuit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shirt',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shoe',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sportswear',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='swimwear',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
