# Generated by Django 4.0.5 on 2022-07-17 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0002_order_product_blazer_product_jacket_product_jeans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
