# Generated by Django 4.0.5 on 2022-07-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0003_remove_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computers',
        ),
    ]
