# Generated by Django 4.0.5 on 2022-07-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0004_delete_computers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sleepwear',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
